//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctorbooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int apid { get; set; }
        public string drloc { get; set; }
        public int drcid { get; set; }
        public int patid { get; set; }
        public string pname { get; set; }
        public string time { get; set; }
        public System.DateTime bookingdate { get; set; }
        public string ailments { get; set; }
        public Nullable<bool> cancelled { get; set; }
        public Nullable<bool> consulted { get; set; }
        public Nullable<decimal> feepaid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual patientreg patientreg { get; set; }
    }
}
