//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctorbooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class drspecialisation
    {
        public int Id { get; set; }
        public int drid { get; set; }
        public int spid { get; set; }
        public int year_exp { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual spectab spectab { get; set; }
    }
}
