//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctorbooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int tid { get; set; }
        public string pname { get; set; }
        public int testamt { get; set; }
        public string docname { get; set; }
    }
}
